// This file will be auto-generated by Supabase CLI
// For now, we'll use the types defined in types/index.ts
// To generate this file, run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/supabase.ts

export type Database = Record<string, unknown> // Will be auto-generated